server:
  port: 9090

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # this works to load schema.sql and data.sql
  h2:
    console:
      enabled: true
      path: /h2_console

