create TABLE  USER (
ID BIGINT NOT NULL AUTO_INCREMENT,
 FIRST_NAME varchar(200) NOT NULL,
 LAST_NAME varchar(200) NOT NULL,
 EMAIL varchar(200) NOT NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE USER_COURSE(
    USER_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    PRIMARY KEY(USER_ID,COURSE_ID)
);