server:
  port: 8762
  
spring:
  application:
    name: zuul-gateway-service

# Eureka server url         
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

zuul:
  prefix: /api
  ignored-services:
  - '*'
  routes:
    userservice:
      path: /users/**
      service-id: user-service
    courserservice:
      path: /courses/**
      service-id: course-service